apiVersion: zarf.dev/v1alpha1
kind: ZarfPackageConfig
metadata:
  name: hello-world
  version: 0.0.1

components:
  - name: hello-world-app
    required: true
    manifests:
    - name: hello-world-deployment
      namespace: hello-world
      kustomizations:
      - https://github.com/millerjem/zarf-hello-world/kustomize?ref=main
    images:
      - docker.io/millerjohe607/zarf-hello-world:latest
